### PR TITLE
Add B827EBFFFE46F9DA.json to master

### PR DESCRIPTION
**Pull request by ElectronicallyE**
Could you please add my file to the master?

Many thanks.

### CODE REVIEW

**Comment by gonzalocasas** [comment]
Done! Please consider adding at least a rough location (lat/long) to it later.

**Comment by ElectronicallyE** [comment]
@gonzalocasas will do so once a location is determined.

**Comment by gonzalocasas** [comment]
👍 thx!

**Comment by gonzalocasas** [comment]
Done

**Comment by ElectronicallyE** [comment]
Thanks. Greatly appreciated.

**Pull request merged**
