### PR TITLE
Create B827EBFFFE112233.json

### PR DESCRIPTION
**Pull request by massroukimohamedtaher**
new gateway .. my first

### CODE REVIEW

**Comment by gonzalocasas** [comment]
Do you really have that ID ending with `112233` or did you create that yourself?

**Comment by massroukimohamedtaher** [comment]
I create it using this commands :

sudo ifconfig eth0 down

sudo ifconfig eth0 hw ether 08:00:00:00:00:01

ifconfig eth0 up


Le lun. 30 sept. 2019 à 17:15, Gonzalo Casas <notifications@github.com> a
écrit :

**Comment by gonzalocasas** [comment]
@massroukimohamedtaher why would you spoof your MAC address?

**Comment by gonzalocasas** [comment]
Please update this PR with the factory assigned MAC address, otherwise I will close it in a few days.

**Comment by gonzalocasas** [comment]
Closing due to lack of activity.

**Pull request closed without merging**
