### PR TITLE
Create B827EBFFFEC64F0E

### PR DESCRIPTION
**Pull request by Arceth**

### CODE REVIEW

**Review by gonzalocasas — CHANGES_REQUESTED** [review]
This file seems to be duplicate: it's missing the `.json` extension, but if I try to add it, I noticed the file already exists. Ok to close?

**Comment by Arceth** [comment]
Yes I know, It´s because the gateways which I use in my project have been registered here by another person before (in his project), but I am currently working with them, would it be possible to use my file as primary?

**Comment by gonzalocasas** [comment]
Aha! Yes, sure, but the other person should confirm. It is @eversio55, right? 

@eversio55: could you please confirm you're ok with replacing the gateway configuration file with the one provided by @Arceth?

**Comment by eversio55** [comment]
Yes, it is ok

Dňa po 28. 3. 2022, 10:50 Gonzalo Casas ***@***.***>
napísal(a):

**Comment by gonzalocasas** [comment]
Thanks!

**Review by gonzalocasas — APPROVED** [review]

**Pull request merged**
