### PR TITLE
Create b827ebfffedbfec8.json

### PR DESCRIPTION
**Pull request by khusboosingh**

### CODE REVIEW

**Comment by khusboosingh** [comment]
I did changed to uppercase but still the status is showing not connected.
What should I do? What might the problem behind this?

**Comment by gonzalocasas** [comment]
I just merged, now you can try again. You might need to re-install.

**Comment by khusboosingh** [comment]
Reinstall the whole setup?

**Comment by gonzalocasas** [comment]
Well, no, you don't have to, the easiest is to pull the remote config repo again and that should do it. In detail, what happened is that you finished the install without waiting for the file to be merged, the install symlinks this file you just created to the `local_conf.json` one inside the packet forwarded, and now, it has a link to nothing because the file was not there yet when the repo was cloned. If you pull, the symlink might just start working and then everyone is happy, but it could also be that it doesn't -I'm not sure-, and in that case, you need to re-link the file. Which you can do by hand if you know what you're doing, or you can trigger the whole `install.sh` again and have it done for you.

**Comment by khusboosingh** [comment]
I reinstalled it but still I didn't say connected. Can you send me the
whole procedure of doing it?

**Comment by gonzalocasas** [comment]
Could you please check the log files and understand why is it failing? There is not procedure besides what is documented on the wiki, plus the clarifications I posted above.. it could be failing for lots of different reasons, maybe wiring is wrong, maybe power supply is not sufficient, or SPI is not enabled, maybe the symlink I mentioned didn't really reinstate properly, without a logfile, I have no clue what's going on...

**Pull request merged**
