### PR TITLE
Create B827EBFFFE99F8C7.json

### PR DESCRIPTION
**Pull request by mbruj**

### CODE REVIEW

**Comment by mbruj** [comment]
@gonzalocasas, not sure if I have done it correctly. I did something, but not really sure what. Let me know whether it will work now.

**Comment by gonzalocasas** [comment]
Perfect! Now it's merged!

**Comment by mbruj** [comment]
@gonzalocasas perfect, I can see something on my gateway. for example" RF packets received by concentrator: 1". I assume that my gateway is working now. However, I have still problem registering the gateway. I thought that I will see it "connected" on TTN console. I can still see "not connected" status and it is not visible on the map. Do you have any clue why?

**Comment by gonzalocasas** [comment]
The status on the console (in V2) is not very reliable to be honest, so, as long as you see packets coming in and your device works, then it's fine.

**Pull request merged**
