### PR TITLE
create B827EBFFFE681695.json

### PR DESCRIPTION
**Pull request by wysi**

### CODE REVIEW

**Comment by gonzalocasas** [comment]
Hi @wysi ! there's a mistake in your json, a missing comma at the end of line 12, please fix it so that we can merge this. cheers!

**Comment by wysi** [comment]
Hi @gonzalocasas ! Thx for your help.
The ttn-gateway service is running, but on the ttn website I see no activity for the gateway.

See the attached /var/log/syslog file.
[log_ttn_gateway3.txt](https://github.com/ttn-zh/gateway-remote-config/files/850919/log_ttn_gateway3.txt)

Do you know what went wrong with my configuration?

**Comment by wysi** [comment]
On the console.thethingsnetwork.org I see traffic from my node to my gateway.
Success!

But on the console in the menu gateway there is written Last Seen: ?
Does the Gateway Overview not work?

**Comment by tamberg** [comment]
@wysi please join the TTN ZH Slack for support questions https://ttn-ch.herokuapp.com/

**Pull request merged**
