### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by pitbayer**

### CODE REVIEW

**Comment by pitbayer** [comment]
thanks...

**Comment by pitbayer** [comment]
please add B827EBFFFE8A53A8.json

**Comment by pitbayer** [comment]
please add B827EBFFFE8A53A8.json

**Comment by pitbayer** [comment]
pls addd b827ebfffe8a53a8.json

**Comment by pitbayer** [comment]
Hi Gonzalo

I try to create a pull request to get the attached file into your repository - I assume I do something not the correct way! The file in question is attached to this email - could you upload/help me?

Kind regards
Peter Christen

**Comment by gonzalocasas** [comment]
@pitbayer the email you replied to was sent to the github servers, not to myself, and github attached the comment, but not the file, so I cannot attach it. On the other hand, please, check any of the multitude of tutorials online about how to create a pull request, e.g. [this one](https://guides.github.com/activities/hello-world/#pr) or [this other one](https://thenewstack.io/getting-legit-with-git-and-github-your-first-pull-request/). You might want to delete your fork, and start from scratch to be on a clean state.

Cheers

**Comment by pitbayer** [comment]
Hi Gonzalo

Thanks for your very quick response - sure I will try again - tsk for the links!
This is my 2nd evening on it and I am positive I am doing the same thing wrong over and over :-)

Take care
Peter

**Pull request closed without merging**
