### PR TITLE
Create B827EBFFFE140769.json

### PR DESCRIPTION
**Pull request by hyecsy**
For getting a project done. Thank you :)

### CODE REVIEW

**Comment by hyecsy** [comment]
My gateway is still not connected to Things Network. Is this due to the B827EBFFFE140769.json file is not merged yet? Thank you

**Comment by hyecsy** [comment]
FYI, I have added this file via github interface and manually inserted from other examples. And modified the information to my own.

**Comment by gonzalocasas** [comment]
It could be due to that. If you installed, and selected remote config, please try a full restart of the gateway, it will pull this repo and then the file that it needs should be in place.

**Comment by hyecsy** [comment]
> It could be due to that. If you installed, and selected remote config, please try a full restart of the gateway, it will pull this repo and then the file that it needs should be in place.

Amazing! Thank you Gonzalocasas

**Comment by hyecsy** [comment]
jut one question, what is fake GPS option is used for? I removed it.

**Comment by gonzalocasas** [comment]
I can't recall what it was for :P

**Pull request merged**
