### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by MikeAtARM**
Add new LoRa GW

### CODE REVIEW

**Comment by gonzalocasas** [comment]
@MikeAtARM I don't know what happened but the content of your json file is totally not what you want in there ;)

**Comment by gonzalocasas** [comment]
@MikeAtARM the content of your file is not the `template.json` but instead is an HTML file (from Github):

image

**Comment by MikeAtARM** [comment]
Corrected small json file. Hope it'll works.

**Comment by gonzalocasas** [comment]
👍😎

**Pull request merged**
