### PR TITLE
14ABC5FFFEF21796

### PR DESCRIPTION
**Pull request by Khainguyen1349**
{ 
	"gateway_conf": { 
		"gateway_ID": "14ABC5FFFEF21796", 
		"servers": [ 
			{ 
				"server_address": "router.eu.thethings.network", 
				"serv_port_up": 1700, 
				"serv_port_down": 1700, 
				"serv_enabled": true 
			} 
		], 
		"ref_latitude": 43.6194002, 
		"ref_longitude": 7.0825769, 
		"ref_altitude": 21, 
		"contact_email": "khai.nguyen@unice.fr", 
		"description": "First gateway in University Cote d'Azur" 
	} 
}

### CODE REVIEW

**Comment by gonzalocasas** [comment]
@Khainguyen1349 I could merge this now, but your comment confuses me. You have one gateway ID and file content in comments, and a completely different one -including different emails address- on the actual commits. Which one is correct?

**Comment by Khainguyen1349** [comment]
Sorry, I totally forgot I use quangkhai1349 mail for git. How can I change the contact_email to "quangkhai1349@gmail.com", please?

**Comment by gonzalocasas** [comment]
Ok, this is weird, because that would be a third email. The one you used now is `eng.aljohania@gmail.com`. I notice that your fork comes from a different user' repo, are you sure the file is really the one you want to merge?

**Comment by gonzalocasas** [comment]
I mean, this is the content that you're trying to merge now:

image

**Comment by Khainguyen1349** [comment]
the B827... is not from me? to pull a request I randomly chose a branch and it seems to be connected to the one from Aljohania. I'm totally new with github, sorry for this inconvenient. How can I fix this please?

**Comment by gonzalocasas** [comment]
No, you cannot choose a branch randomly, you need to create a new pull request, with a new file that will create a new branch.

**Comment by Khainguyen1349** [comment]
OK, I will try it again. please note that the json file B827EB... is not from me and you can ignore the one with 14ABC... Thank a lots.

**Comment by gonzalocasas** [comment]
@Khainguyen1349 Ok, I closed this one now. Please create a new one, you can easily do this from the Github web interface:

image

In there, you can upload your file.  😄

**Pull request closed without merging**
