### PR TITLE
Update B827EBFFFF27E9C2.json

### PR DESCRIPTION
**Pull request by mftutui**

### CODE REVIEW

**Comment by gonzalocasas** [comment]
@vnoll since you were the one who created this gateway file, do you approve this change? is @mftutui the new owner?

**Comment by gonzalocasas** [comment]
@vnoll @mftutui ping ;)

**Comment by mftutui** [comment]
Waiting @vnoll

**Comment by gonzalocasas** [comment]
@vnoll hello?

**Comment by gonzalocasas** [comment]
Closing due to lack of activity. Feel free to reopen whenever the other gateway owner responds.

**Pull request closed without merging**
