### PR TITLE
Create B827EBFFFFEA394C1.json

### PR DESCRIPTION
**Pull request by tuftec**
Adding details for a new gateway

### CODE REVIEW

**Comment by tuftec** [comment]
Just realised, file name neeeds to have the extension .json
Can you please change when adding to main project.
Thanks Peter.

**Comment by tuftec** [comment]
Incorrect EUI number. Now fixed

**Comment by tuftec** [comment]
How do I change the file name. I believe the contents are ok. Is it not possible to commit this to the new file name? I am not all that experienced with Github.

**Comment by gonzalocasas** [comment]
The content is also not ok, the gateway EUI has one extra digit, it cannot be 17 characters long. So, best would be to create a new pull request, make sure you take the correct EUI, create the file with it + extension, and make sure the EUI is correct inside the file as well.

Regarding Github, please check online, there's a lot of really good material to learn how to use it, and it is generally not very complicated.

I will close this Pull Request for now, so that you can create the new one.

Cheers

**Comment by tuftec** [comment]
Thanks.

 

I will try to fix

 

Peter.

 

 

 

  <file:///C:/tuftec/logoidea9.jpg> 

Peter Stone

CEO

Tuftec Solutions

(Tuftec Pty Ltd, ACN 143 869 970)

+61 425 772 830

E:  peters@Tuftec.com <wlmailhtml:%7b266978EE-3EB9-4476-A0F5-0DF7468C395F%7dmid://00000001/!x-usc:mailto:peters@Tuftec.com>   

W:  www.tuftec.com <http://www.tuftec.com> 

F: +61 3 9763 9955

A: 22 Folkstone Cres, Ferntree Gully, Victoria, Australia, 3156.  

 

Technology Solutions for demanding applications and environments.

___________________________________________________     ______                   ­­­­  ___ 

This is an e-mail from Tuftec Pty Ltd. It is confidential to the ordinary user of the e-mail 

address to which it was addressed and may contain copyright and/or legally privileged information. No 

one else may read, print, store, copy or forward all or any of it or its attachments. If you receive this 

e-mail in error, please return to sender.  The recipient of this e-mail should be aware that this e-mail and 

any attachments to it might not be free from viruses in their various forms. Tuftec strongly 

recommends that the recipient uses anti-virus software to screen all e-mails received externally. 

Tuftec does not accept any liability for any loss or damage that may occur as a result of the 

transmission of this e-mail to the recipient. Any views or opinions presented are solely those of the 

author and do not necessarily represent those of Tuftec. Replies to this email may be monitored 

for operational or business reasons.

**Pull request closed without merging**
