### PR TITLE
Create B827EBFFFE11F166

### PR DESCRIPTION
**Pull request by rangerTech24**

### CODE REVIEW

**Comment by rangerTech24** [comment]
PLEASE ADD!

**Comment by gonzalocasas** [comment]
@rangerTech24 but why do you close the PR if you want to add it?

**Comment by gonzalocasas** [comment]
Also, please use uppercase for the ID in the content of the file, use `.json` extension and add at least a rough location (lat/long). Thanks!

**Comment by gonzalocasas** [comment]
Sorry, now I realize that you sent another PR for the same file long ago and that is merged already! The situation is now evident because this PR has a conflict with the other file you committed long ago. I don't understand then why you reopened this one...?

**Comment by gonzalocasas** [comment]
I'm gonna close it, as obviously there's no need for this anymore. If you still have question, feel free to post them here anyway.

**Pull request closed without merging**
