### PR TITLE
Update B827EBFFFE84C1B8.json

### PR DESCRIPTION
**Pull request by fredjAhmed**

### CODE REVIEW

**Comment by fredjAhmed** [comment]
Hello Gonzalo,
I followed the tutorial on how to build a raspbarry pi based lora gateway.
I am using a raspberry pi zero and i am having a : Failed to start the
concentrator error? how can i fix this please?

2018-03-14 10:51 GMT+01:00 Gonzalo Casas <notifications@github.com>:

**Comment by gonzalocasas** [comment]
There are lots of reasons why this can fail:
 - Double check that SPI is enabled
 - Double and triple check the wiring (if you have jumper wires, consider changing that and using a backplane)
 - Make sure the power supply is good enough and rated at 2A at least, try replacing it also

**Comment by fredjAhmed** [comment]
The SPI is enabled and i dont think i have to enable it in every boot yes?
I am pluging the raspberry with my phone charger directly to the plug so i
think it is more than 2A.
The wiring is what i am afraid of. The raspberry pi zero isn't exactly the
sape as the pi 3 and the problem is i dont know if the wiring is correct. I
tried to put them in the same numbers as in the tutorial.
Do you think it is not possible to do it with the raspberry pi zero?

2018-03-15 16:35 GMT+01:00 Gonzalo Casas <notifications@github.com>:

**Comment by gonzalocasas** [comment]
> The SPI is enabled and i dont think i have to enable it in every boot yes?

Nope, no need to enable it on every boot.

> i think it is more than 2A

Please check, also make sure it's a good one. Chinese clone chargers are not stable many times, and cause this.

>  The raspberry pi zero isn't exactly the sape as the pi 3

I think it is. Where do you see differences? Eventually, you could get one of the several backplanes out there (I did one [available here](https://www.tindie.com/products/gnz/imst-ic880a-lorawan-backplane-kit/), but there are many others as well)

> Do you think it is not possible to do it with the raspberry pi zero?

It is possible. I had a gateway running with a zero.

**Comment by fredjAhmed** [comment]
Ok i will try getting my hands on one of the backplanes and I will check
the current if it is more than 2A.
Can you please share with me the pin wiring of when you used the raspbarry
pi zero to make sure i didn't make any errors? And one last thing, could
you share with me the script of the  lora_pkt_fwd
<https://github.com/Lora-net/packet_forwarder/tree/master/lora_pkt_fwd>?

2018-03-15 17:18 GMT+01:00 Gonzalo Casas <notifications@github.com>:

**Comment by gonzalocasas** [comment]
> Can you please share with me the pin wiring of when you used the raspbarry pi zero

I repeat: the RPi Zero has the same pinout as the RPi 3. So, use the pinout described in the [wiki](https://github.com/ttn-zh/ic880a-gateway/wiki).

> could you share with me the script of the  lora_pkt_fwd

Two questions:
1) what do you mean with "share the script"? Everything is open source, it's already shared.
2) Are you using the `lora_pkt_fwd`? If that is the case, then it means you're following some other instructions, and probably the problem is that your RESET pin is not matching the wiring.

**Comment by fredjAhmed** [comment]
I wanted the shell script of the lora-pkt-fwd because i only got the binary
for that and i wanted to change it.
What do you mean i am not following your instructions? Did you not specify
that you used lora-pkt-fwd?

**Comment by fredjAhmed** [comment]
Yeah, i dont know how to connet to the reset.

**Comment by gonzalocasas** [comment]
No, I am not using the `lora_pkt_fwd`. The instructions I assume you're using are the ones in this repository: https://github.com/ttn-zh/ic880a-gateway/wiki

In there, I use the `poly_pkt_fwd`, not the `lora_pkt_fwd`.

**Comment by fredjAhmed** [comment]
yeah yeah those are the instructions i followed. I mixed up the names
sorry. In here the pin 13 of the ic880a i connected it to the raspberry pi
zero pin 22 like you said but still dont know where the problem is.
Can i ask you which script manipulates the pins of the raspbarry?
and the poly-pkt-fwd i only found its binary. Where can i find the
precompiled one?

2018-03-15 21:48 GMT+01:00 Gonzalo Casas <notifications@github.com>:

**Comment by gonzalocasas** [comment]
The scripts are the `spi` branch of the same repo: https://github.com/ttn-zh/ic880a-gateway/tree/spi
By the way, are you sure you executed the installer with the `spi` flag? `sudo ./install.sh spi`

And then, you'll see that the `install.sh` file (https://github.com/ttn-zh/ic880a-gateway/blob/spi/install.sh) is the one that does the installation, it compiles everything from source, you can read the details of what is pulled and compiled directly in the file.

Afterwards, the `start.sh` file is what starts the concentrator: https://github.com/ttn-zh/ic880a-gateway/blob/spi/start.sh 

The reset pin is configured there, BUT, please notice that the Raspberry PI has 3 (THREE!) different ways of numbering the pins, so, you will see in the script that the reset pin is 25, but that's because this is the BCM notation, and BCM25 == 22. All three notations mapped in this website: https://pinout.xyz/

**Comment by fredjAhmed** [comment]
this is the pinout of the raspberry pi zero? or is it commen to all
raspberry pi? because i had a printed pinout and it didn't look like this.
the locations were changed. maybe then this is my problem


2018-03-15 22:01 GMT+01:00 Gonzalo Casas <notifications@github.com>:

**Comment by gonzalocasas** [comment]
Yes, that is the pinout. It is exactly the same for all modern RPis (the only different ones iirc, are the first models that had only 26 pins, but even then, the pinout of the first 26 pins is the same as the new ones).

**Comment by gonzalocasas** [comment]
Great to hear that!

You can use the downlink for controlling params of the sensor, that's totally ok. As long as you keep within the very tight limit of max 10 downlinks a day per sensor, it's fine.
About ACKs, I wouldn't use confirmed messages, otherwise you will exceed the downlink limit (ACKs also count towards those 10/day).

Cheers

**Comment by fredjAhmed** [comment]
Ok I will follow your instructions. Do you have any example of how i can
use the downlink to send messages beacause i found only tutorials on how to
use the uplink.
Also, in order to edit the informations that are showen on the map of the
gateways do i have to change the json file in your github or the
local-config.json in the raspbarry?

2018-03-16 9:19 GMT+01:00 Gonzalo Casas <notifications@github.com>:

**Comment by gonzalocasas** [comment]
> Do you have any example of how i can use the downlink 

Check this tutorial for Arduino and LMIC, but there's many diffferent ones online:
http://www.tamberg.org/chopen/2017/LoRaWANIoTWorkshop.pdf

> do i have to change the json file in your github
Yes

**Comment by fredjAhmed** [comment]
Ok Thank you Sir so much for your help and advices. If it is not a bother,
If I have an other question in the future can I ask you it?

2018-03-16 13:12 GMT+01:00 Gonzalo Casas <notifications@github.com>:

**Comment by gonzalocasas** [comment]
Yes

**Comment by fredjAhmed** [comment]
ok thank you and have a good day :D

2018-03-16 14:29 GMT+01:00 Gonzalo Casas <notifications@github.com>:

**Pull request merged**
