### PR TITLE
Update B827EBFFFEB4F49F.json

### PR DESCRIPTION
**Pull request by iServe-IT**

### CODE REVIEW

**Comment by gonzalocasas** [comment]
@iServe-IT: woah, what happened here...? :) please always pull before pushing.

**Comment by iServe-IT** [comment]
I made a minor change to my config directly on Github. All the steps showed green buttons and no mention of merge problems. I will not do that again, sorry! Did I break anything?


---
Verstuurd vanaf mijn  iPhone

**Comment by gonzalocasas** [comment]
Looks like everything is good 😁

**Comment by dbrgn** [comment]
This is a merge from master to the B827EBFFFEB4F49F branch, that's why all those commits are there.

**Comment by iServe-IT** [comment]
I also checked of course and could not find any problems. 😊

---
Verstuurd vanaf mijn  iPhone

> Op 24 jan. 2017 om 17:23 heeft Gonzalo Casas <notifications@github.com> het volgende geschreven:
> 
> Looks like everything is good 😁
> 
> On Tue, Jan 24, 2017, 16:43 Stephan Visser @ iServe-IT <

**Pull request merged**
