### PR TITLE
Create B827EBFFFE0060A9

### PR DESCRIPTION
**Pull request by BerndGaykema**
Create B827EBFFFE0060A9

### CODE REVIEW

**Comment by BerndGaykema** [comment]
Hi,

I am trying to make a fresh SD-card for my RPi with your Lora gateway software (ttn-zh/ic880a-gateway).
I did this several times in the past with great success but now I get stuck with the git clone step. 
It says “no such file”…

Is there something changed in the github?

The only difference at my site is that I now use the light BUSTER version instead of Stretch.

Please help me as I would like to have my gateway in the air a.s.a.p.

Thank you

With best regards,
Bernd Gaykema

 

Van: Gonzalo Casas <notifications@github.com> 
Verzonden: zaterdag 13 januari 2018 18:33
Aan: ttn-zh/gateway-remote-config <gateway-remote-config@noreply.github.com>
CC: BerndGaykema <bernd@gaykema.com>; State change <state_change@noreply.github.com>
Onderwerp: Re: [ttn-zh/gateway-remote-config] Create B827EBFFFE0060A9 (#463)

 

Merged #463 <https://github.com/ttn-zh/gateway-remote-config/pull/463> .

**Comment by gonzalocasas** [comment]
Please post the full console output including the command you are issuing.
I don't see why the clone step would not work on Buster.

**Comment by BerndGaykema** [comment]
The yellow line is the error message

 

ttn@raspberrypi:~ $ git clone https://github.com/ttn-zh/ic880a-gateway.git ~/ic880a-gateway

Cloning into '/home/ttn/ic880a-gateway'...

/usr/lib/git-core/git-remote-https: error while loading shared libraries: er▒: cannot open shared object file: No such file or directory

ttn@raspberrypi:~ $

 

 

 

Van: Gonzalo Casas <notifications@github.com> 
Verzonden: dinsdag 5 november 2019 19:43
Aan: ttn-zh/gateway-remote-config <gateway-remote-config@noreply.github.com>
CC: BerndGaykema <bernd@gaykema.com>; State change <state_change@noreply.github.com>
Onderwerp: Re: [ttn-zh/gateway-remote-config] Create B827EBFFFE0060A9 (#463)

 

Please post the full console output including the command you are issuing.
I don't see why the clone step would not work on Buster.

**Comment by gonzalocasas** [comment]
Please post it on GitHub web interface, not over email because all formatting is gone.

**Comment by BerndGaykema** [comment]
Done.
First time ever …..

 

Van: Gonzalo Casas <notifications@github.com> 
Verzonden: dinsdag 5 november 2019 20:17
Aan: ttn-zh/gateway-remote-config <gateway-remote-config@noreply.github.com>
CC: BerndGaykema <bernd@gaykema.com>; State change <state_change@noreply.github.com>
Onderwerp: Re: [ttn-zh/gateway-remote-config] Create B827EBFFFE0060A9 (#463)

 

Please post it on GitHub web interface, not over email because all formatting is gone.

**Comment by gonzalocasas** [comment]
Mmm...sorry but I still don't see it. where did you post it? On this thread I only see the unformatted text coming from the email stuff. No yellow line, no formatting, nothing. In any case, I seriously doubt this error has anything to do with the LoRaWAN stuff, this looks like a problem with the setup...

**Comment by BerndGaykema** [comment]
https://github.com/ttn-zh/ic880a-gateway/issues

 

Van: Gonzalo Casas <notifications@github.com> 
Verzonden: dinsdag 5 november 2019 20:37
Aan: ttn-zh/gateway-remote-config <gateway-remote-config@noreply.github.com>
CC: BerndGaykema <bernd@gaykema.com>; State change <state_change@noreply.github.com>
Onderwerp: Re: [ttn-zh/gateway-remote-config] Create B827EBFFFE0060A9 (#463)

 

Mmm...sorry but I still don't see it. where did you post it? On this thread I only see the unformatted text coming from the email stuff. No yellow line, no formatting, nothing. In any case, I seriously doubt this error has anything to do with the LoRaWAN stuff, this looks like a problem with the setup...

**Comment by BerndGaykema** [comment]
https://github.com/ttn-zh/ic880a-gateway/issues/64

 

So issue 64

 

Van: Bernd Gaykema <bernd@gaykema.com> 
Verzonden: dinsdag 5 november 2019 20:40
Aan: 'ttn-zh/gateway-remote-config' <reply@reply.github.com>
Onderwerp: RE: [ttn-zh/gateway-remote-config] Create B827EBFFFE0060A9 (#463)

 

https://github.com/ttn-zh/ic880a-gateway/issues

 

Van: Gonzalo Casas <notifications@github.com <mailto:notifications@github.com> > 
Verzonden: dinsdag 5 november 2019 20:37
Aan: ttn-zh/gateway-remote-config <gateway-remote-config@noreply.github.com <mailto:gateway-remote-config@noreply.github.com> >
CC: BerndGaykema <bernd@gaykema.com <mailto:bernd@gaykema.com> >; State change <state_change@noreply.github.com <mailto:state_change@noreply.github.com> >
Onderwerp: Re: [ttn-zh/gateway-remote-config] Create B827EBFFFE0060A9 (#463)

 

Mmm...sorry but I still don't see it. where did you post it? On this thread I only see the unformatted text coming from the email stuff. No yellow line, no formatting, nothing. In any case, I seriously doubt this error has anything to do with the LoRaWAN stuff, this looks like a problem with the setup...

**Comment by gonzalocasas** [comment]
Ah! 👍

**Pull request merged**
