### PR TITLE
Create B827EBFFFEC9AA92.json

### PR DESCRIPTION
**Pull request by ares1876**
Creating a new .json file in order to configure my gateway for connecting with TTN.

### CODE REVIEW

**Comment by ares1876** [comment]
Request to join my gateway to The Things Network!

**Comment by ares1876** [comment]
Hello,
Even though you merged out file with the main project our gateway status is still "not connected" in the TTN console.
Below are the log files of our gateway.

total 35412
-rw-r--r-- 1 root root     3985 Mar 19 13:58 alternatives.log
drwxr-xr-x 2 root root     4096 Apr 10  2017 apt
-rw-r----- 1 root adm     12295 Mar 23 14:17 auth.log
-rw-r----- 1 root adm     55029 Mar 21 06:25 auth.log.1
-rw-r----- 1 root adm      4607 Mar 11 06:25 auth.log.2.gz
-rw-r--r-- 1 root root     4399 Mar 23 14:17 boot.log
-rw-r--r-- 1 root root        0 Apr 10  2017 bootstrap.log
-rw------- 1 root utmp     5760 Mar 20 16:48 btmp
-rw-r----- 1 root adm   9005539 Mar 23 14:33 daemon.log
-rw-r----- 1 root adm  18417403 Mar 21 06:23 daemon.log.1
-rw-r----- 1 root adm    358406 Mar 11 06:22 daemon.log.2.gz
-rw-r----- 1 root adm      1818 Mar 23 14:17 debug
-rw-r----- 1 root adm     15638 Mar 20 17:06 debug.1
-rw-r----- 1 root adm      1968 Mar  9 11:31 debug.2.gz
-rw-r----- 1 root adm         0 Apr 10  2017 dmesg
-rw-r--r-- 1 root root   184701 Mar 19 13:58 dpkg.log
-rw-r--r-- 1 root root    24072 Mar 20 17:03 faillog
-rw-r--r-- 1 root root        0 Apr 10  2017 fontconfig.log
drwxr-xr-x 2 root root     4096 Apr 10  2017 fsck
-rw-r----- 1 root adm     28957 Mar 23 14:32 kern.log
-rw-r----- 1 root adm   1115684 Mar 20 17:06 kern.log.1
-rw-r----- 1 root adm     35297 Mar  9 16:38 kern.log.2.gz
-rw-rw-r-- 1 root utmp   292876 Mar 23 14:17 lastlog
drwx--x--x 2 root root     4096 Mar 23 14:17 lightdm
-rw-r----- 1 root adm    181564 Mar 23 14:33 messages
-rw-r----- 1 root adm    536451 Mar 21 06:25 messages.1
-rw-r----- 1 root adm     59422 Mar 11 06:25 messages.2.gz
drwxr-xr-x 2 ntp  ntp      4096 Jul 26  2016 ntpstats
drwxr-x--- 2 root adm      4096 Apr  1  2017 samba
-rw-r----- 1 root adm   1391934 Mar 23 14:33 syslog
-rw-r----- 1 root adm   3896665 Mar 23 06:25 syslog.1
-rw-r----- 1 root adm     86848 Mar 22 06:25 syslog.2.gz
-rw-r----- 1 root adm    185830 Mar 21 06:25 syslog.3.gz
-rw-r----- 1 root adm    115313 Mar 15 06:25 syslog.4.gz
-rw-r----- 1 root adm    114395 Mar 14 06:25 syslog.5.gz
-rw-r----- 1 root adm    111977 Mar 13 06:25 syslog.6.gz
-rw-r----- 1 root adm     84074 Mar 12 06:25 syslog.7.gz
-rw-r----- 1 root adm        88 Mar 23 14:17 user.log
-rw-r----- 1 root adm      4204 Mar 20 17:06 user.log.1
-rw-r----- 1 root adm       617 Mar  9 11:31 user.log.2.gz
-rw-rw-r-- 1 root utmp    66432 Mar 23 14:17 wtmp
-rw-r--r-- 1 root root    12093 Mar 23 14:17 Xorg.0.log
-rw-r--r-- 1 root root    16384 Mar 23 14:32 Xorg.0.log.old

Can you please tell us what we did wrong?

**Comment by gonzalocasas** [comment]
> Below are the log files of our gateway.

No, sorry, you just posted a list of file names, that is not a log. Please, do take your time to find and post your system logfiles here.

**Comment by ares1876** [comment]
Hello Sir,
As it seems the file which we created B827EBFFFEC9AA92.json is not the same with our local_conf.json, because of this our gateway status in ttn console is not connected. 
The logfiles of our configuration are as below.
We think the problem stands in the coordinates, but we don't know how to reconfigure them in our gateway.
Can you please help us fix the problem?


Mar 23 15:16:51 stuttn-gateway ttn-gateway[1724]: INFO: Platform configured to "IMST + Rpi"
Mar 23 15:16:51 stuttn-gateway ttn-gateway[1724]: INFO: Contact email configured to "operator@gateway.tst"
Mar 23 15:16:51 stuttn-gateway ttn-gateway[1724]: INFO: Description configured to "Update me"
Mar 23 15:16:51 stuttn-gateway ttn-gateway[1724]: INFO: found local configuration file local_conf.json, parsing it
Mar 23 15:16:51 stuttn-gateway ttn-gateway[1724]: INFO: redefined parameters will overwrite global parameters
Mar 23 15:16:51 stuttn-gateway ttn-gateway[1724]: ERROR: local_conf.json is not a valid JSON file
Mar 23 15:16:56 stuttn-gateway systemd[1]: ttn-gateway.service holdoff time over, scheduling restart.
Mar 23 15:16:56 stuttn-gateway systemd[1]: Stopping The Things Network Gateway...
Mar 23 15:16:56 stuttn-gateway systemd[1]: Starting The Things Network Gateway...
Mar 23 15:16:56 stuttn-gateway systemd[1]: Started The Things Network Gateway.
Mar 23 15:17:01 stuttn-gateway CRON[1817]: (root) CMD (   cd / && run-parts --report /etc/cron.hourly)
Mar 23 15:17:02 stuttn-gateway ttn-gateway[1789]: /opt/ttn-gateway/gateway-remote-config /opt/ttn-gateway/bin
Mar 23 15:17:09 stuttn-gateway ttn-gateway[1789]: Already up-to-date.
Mar 23 15:17:09 stuttn-gateway ttn-gateway[1789]: HEAD is now at b929f30 Merge pull request #640 from hellwig/master
Mar 23 15:17:09 stuttn-gateway ttn-gateway[1789]: /opt/ttn-gateway/bin
Mar 23 15:17:09 stuttn-gateway ttn-gateway[1789]: [TTN Gateway]: Use Gateway EUI B827EBFFFEC9AA92 based on eth0
Mar 23 15:17:09 stuttn-gateway ttn-gateway[1789]: *** Poly Packet Forwarder for Lora Gateway ***
Mar 23 15:17:09 stuttn-gateway ttn-gateway[1789]: Version: 2.1.0
Mar 23 15:17:09 stuttn-gateway ttn-gateway[1789]: *** Lora concentrator HAL library version info ***
Mar 23 15:17:09 stuttn-gateway ttn-gateway[1789]: Version: 3.1.0; Options: native;
Mar 23 15:17:09 stuttn-gateway ttn-gateway[1789]: ***
Mar 23 15:17:09 stuttn-gateway ttn-gateway[1789]: INFO: Little endian host
Mar 23 15:17:09 stuttn-gateway ttn-gateway[1789]: INFO: found global configuration file global_conf.json, parsing it
Mar 23 15:17:09 stuttn-gateway ttn-gateway[1789]: INFO: global_conf.json does contain a JSON object named SX1301_conf, parsing SX1301 parameters
Mar 23 15:17:09 stuttn-gateway ttn-gateway[1789]: INFO: lorawan_public 1, clksrc 1
Mar 23 15:17:09 stuttn-gateway ttn-gateway[1789]: INFO: Configuring TX LUT with 16 indexes
Mar 23 15:17:09 stuttn-gateway ttn-gateway[1789]: INFO: radio 0 enabled (type SX1257), center frequency 867500000, RSSI offset -166.000000, tx enabled 1
Mar 23 15:17:09 stuttn-gateway ttn-gateway[1789]: INFO: radio 1 enabled (type SX1257), center frequency 868500000, RSSI offset -166.000000, tx enabled 0
Mar 23 15:17:09 stuttn-gateway ttn-gateway[1789]: INFO: Lora multi-SF channel 0>  radio 1, IF -400000 Hz, 125 kHz bw, SF 7 to 12
Mar 23 15:17:09 stuttn-gateway ttn-gateway[1789]: INFO: Lora multi-SF channel 1>  radio 1, IF -200000 Hz, 125 kHz bw, SF 7 to 12
Mar 23 15:17:09 stuttn-gateway ttn-gateway[1789]: INFO: Lora multi-SF channel 2>  radio 1, IF 0 Hz, 125 kHz bw, SF 7 to 12
Mar 23 15:17:09 stuttn-gateway ttn-gateway[1789]: INFO: Lora multi-SF channel 3>  radio 0, IF -400000 Hz, 125 kHz bw, SF 7 to 12
Mar 23 15:17:09 stuttn-gateway ttn-gateway[1789]: INFO: Lora multi-SF channel 4>  radio 0, IF -200000 Hz, 125 kHz bw, SF 7 to 12
Mar 23 15:17:09 stuttn-gateway ttn-gateway[1789]: INFO: Lora multi-SF channel 5>  radio 0, IF 0 Hz, 125 kHz bw, SF 7 to 12
Mar 23 15:17:09 stuttn-gateway ttn-gateway[1789]: INFO: Lora multi-SF channel 6>  radio 0, IF 200000 Hz, 125 kHz bw, SF 7 to 12
Mar 23 15:17:09 stuttn-gateway ttn-gateway[1789]: INFO: Lora multi-SF channel 7>  radio 0, IF 400000 Hz, 125 kHz bw, SF 7 to 12
Mar 23 15:17:09 stuttn-gateway ttn-gateway[1789]: INFO: Lora std channel> radio 1, IF -200000 Hz, 250000 Hz bw, SF 7
Mar 23 15:17:09 stuttn-gateway ttn-gateway[1789]: INFO: FSK channel> radio 1, IF 300000 Hz, 125000 Hz bw, 50000 bps datarate
Mar 23 15:17:09 stuttn-gateway ttn-gateway[1789]: INFO: global_conf.json does contain a JSON object named gateway_conf, parsing gateway parameters
Mar 23 15:17:09 stuttn-gateway ttn-gateway[1789]: INFO: gateway MAC address is configured to AA555A0000000000
Mar 23 15:17:09 stuttn-gateway ttn-gateway[1789]: INFO: Found 2 servers in array.
Mar 23 15:17:09 stuttn-gateway ttn-gateway[1789]: INFO: Server 0 configured to "127.0.0.1", with port up "1680" and port down "1681"
Mar 23 15:17:09 stuttn-gateway ttn-gateway[1789]: INFO: Server 1 configured to "iot.semtech.com", with port up "1680" and port down "1680"
Mar 23 15:17:09 stuttn-gateway ttn-gateway[1789]: INFO: Found 5 system calls in array.
Mar 23 15:17:09 stuttn-gateway ttn-gateway[1789]: INFO: System command 0: "df -m"
Mar 23 15:17:09 stuttn-gateway ttn-gateway[1789]: INFO: System command 1: "free -h"
Mar 23 15:17:09 stuttn-gateway ttn-gateway[1789]: INFO: System command 2: "uptime"
Mar 23 15:17:09 stuttn-gateway ttn-gateway[1789]: INFO: System command 3: "who -a"
Mar 23 15:17:09 stuttn-gateway ttn-gateway[1789]: INFO: System command 4: "uname -a"
Mar 23 15:17:09 stuttn-gateway ttn-gateway[1789]: INFO: monitor hostname or IP address is configured to "127.0.0.1"
Mar 23 15:17:09 stuttn-gateway systemd[1]: ttn-gateway.service: main process exited, code=exited, status=1/FAILURE
Mar 23 15:17:09 stuttn-gateway systemd[1]: Unit ttn-gateway.service entered failed state.
Mar 23 15:17:09 stuttn-gateway ttn-gateway[1789]: INFO: monitor port is configured to "2008"
Mar 23 15:17:09 stuttn-gateway ttn-gateway[1789]: INFO: ghost hostname or IP address is configured to "127.0.0.1"
Mar 23 15:17:09 stuttn-gateway ttn-gateway[1789]: INFO: ghost port is configured to "1918"
Mar 23 15:17:09 stuttn-gateway ttn-gateway[1789]: INFO: downstream keep-alive interval is configured to 10 seconds
Mar 23 15:17:09 stuttn-gateway ttn-gateway[1789]: INFO: statistics display interval is configured to 30 seconds
Mar 23 15:17:09 stuttn-gateway ttn-gateway[1789]: INFO: upstream PUSH_DATA time-out is configured to 100 ms
Mar 23 15:17:09 stuttn-gateway ttn-gateway[1789]: INFO: packets received with a valid CRC will be forwarded
Mar 23 15:17:09 stuttn-gateway ttn-gateway[1789]: INFO: packets received with a CRC error will NOT be forwarded
Mar 23 15:17:09 stuttn-gateway ttn-gateway[1789]: INFO: packets received with no CRC will NOT be forwarded
Mar 23 15:17:09 stuttn-gateway ttn-gateway[1789]: INFO: GPS serial port path is configured to "/dev/ttyAMA0"
Mar 23 15:17:09 stuttn-gateway ttn-gateway[1789]: INFO: SSH path is configured to "/usr/bin/ssh"
Mar 23 15:17:09 stuttn-gateway ttn-gateway[1789]: INFO: SSH port is configured to 22
Mar 23 15:17:09 stuttn-gateway ttn-gateway[1789]: INFO: HTTP port is configured to 80
Mar 23 15:17:09 stuttn-gateway ttn-gateway[1789]: INFO: NGROK path is configured to "/usr/bin/ngrok"
Mar 23 15:17:09 stuttn-gateway ttn-gateway[1789]: INFO: Reference latitude is configured to 10.000000 deg
Mar 23 15:17:09 stuttn-gateway ttn-gateway[1789]: INFO: Reference longitude is configured to 20.000000 deg
Mar 23 15:17:09 stuttn-gateway ttn-gateway[1789]: INFO: Reference altitude is configured to -1 meters
Mar 23 15:17:09 stuttn-gateway ttn-gateway[1789]: INFO: GPS is enabled
Mar 23 15:17:09 stuttn-gateway ttn-gateway[1789]: INFO: Using fake GPS coordinates instead of real.
Mar 23 15:17:09 stuttn-gateway ttn-gateway[1789]: INFO: antenna_gain 0 dBi
Mar 23 15:17:09 stuttn-gateway ttn-gateway[1789]: INFO: Upstream data is enabled
Mar 23 15:17:09 stuttn-gateway ttn-gateway[1789]: INFO: Downstream data is enabled
Mar 23 15:17:09 stuttn-gateway ttn-gateway[1789]: INFO: Ghoststream data is disabled
Mar 23 15:17:09 stuttn-gateway ttn-gateway[1789]: INFO: Radiostream data is enabled
Mar 23 15:17:09 stuttn-gateway ttn-gateway[1789]: INFO: Statusstream data is enabled
Mar 23 15:17:09 stuttn-gateway ttn-gateway[1789]: INFO: Beacon is disabled
Mar 23 15:17:09 stuttn-gateway ttn-gateway[1789]: INFO: Monitor is disabled
Mar 23 15:17:09 stuttn-gateway ttn-gateway[1789]: INFO: Platform configured to "IMST + Rpi"
Mar 23 15:17:09 stuttn-gateway ttn-gateway[1789]: INFO: Contact email configured to "operator@gateway.tst"
Mar 23 15:17:09 stuttn-gateway ttn-gateway[1789]: INFO: Description configured to "Update me"
Mar 23 15:17:09 stuttn-gateway ttn-gateway[1789]: INFO: found local configuration file local_conf.json, parsing it
Mar 23 15:17:09 stuttn-gateway ttn-gateway[1789]: INFO: redefined parameters will overwrite global parameters
Mar 23 15:17:09 stuttn-gateway ttn-gateway[1789]: ERROR: local_conf.json is not a valid JSON file

**Comment by gonzalocasas** [comment]
Ok, yes, the file you uploaded is indeed *invalid* JSON, so, it won't work. I just fixed it on the repository, so try the following:
 1) restart and check logs. On restart, the system pulls from this repository, so if everything is correctly configured, it will pull the fixed file and hopefully start working.
 2) if that doesn't work, re-start the installation, it could be that you have some local change or issue that is blocking it.

**Comment by ares1876** [comment]
It is fixed. The status now is "connected".

Thanks a lot for the help.

**Pull request merged**
