### PR TITLE
Update B827EBFFFE3B5B2E.json

### PR DESCRIPTION
**Pull request by sosnus**

### CODE REVIEW

**Comment by gonzalocasas** [comment]
@nilsonwolf since you're the current owner of this gateway, do you confirm this change?

**Comment by sosnus** [comment]
Yes, I'm current owner of this gateway. Thank You for attention :)
https://ttn-tul.readthedocs.io/en/latest/Gateways/Our%20Gateways/

**Comment by gonzalocasas** [comment]
@sosnus ok, but I need @nilsonwolf to confirm first.

**Comment by gonzalocasas** [comment]
Thanks!

**Comment by sosnus** [comment]
Thanks @gonzalocasas  @nilsonwolf  !

**Pull request merged**
